### ISSUE TITLE
After uninstalling Switcher system stopped freezing

### ISSUE THREAD

**Issue by diogopessoa** [JeysonFlores/switcher#19]
hello mate;

since yesterday elementary 6.1 Jólnir (all updated) started to freeze after system boot. 
After several unsolved tests, I went into TTY mode and uninstalled Switcher and elementary stopped freezing on my two machines.
This happened on my laptop and my PC.

OS and Hardware:
elementary OS 6.1 Jólnir
Linux 5.13.0-28-generic
Dual-Core Intel Core i5
7,6 GiB memory

**Comment by lukors** [comment]
This is very concerning!

I noticed we have slightly different kernel versions. Mine is `5.13.0-7620`, and yours is `5.13.0-28`. I had issues with my computer locking up under certain conditions when I once accidentally installed another kernel version, do you think this could be similar? I don't know if that last number in the version makes any difference at all, and my Internet searches hasn't come up with anything conclusive.

Do you remember anything about how you had Switcher configured? Used default wallpapers? Could the wallpaper you were using for Switcher have been removed? Anything else relevant you can think of that might have caused it?

Thanks for the report! :smile:

**Comment by diogopessoa** [comment]
The kernel on my two machines is elementary's default. I didn't make any changes.
Are you not using the testing version of elementary?
I had configured the Switcher with the official wallpapers and the schedule was like this: light 06:00 and dark 17:20.

I remembered one detail. The switcher was installed in system-wide. I don't know if it makes any difference.
![Screenshot from 2022-02-04 12 30 15](https://user-images.githubusercontent.com/12633864/152556231-fee645ba-4000-4d62-b7bc-721b19beae3a.png)

**Comment by lukors** [comment]
As far as I know I'm not using the testing version of elementary.

The system-wide install could be relevant, thanks for the extra information! Don't hesitate to write again if you remember something else that might be relevant. :smile:

**Comment by JeysonFlores** [comment]
This issue is weird af, Switcher doesn't make anything special regardless to the system and due to Flatpak's sandboxing this shouldn't happen. Let's keep this issue open if this happens to more people.

**Comment by itoshkov** [comment]
I can confirm that the issue is present on my machine as well. The computer freezes shortly after I log in, but only with kernel 5.13.0-28-generic. If I go back to 5.13.0-27-generic, it's working fine.

Additional notes, I'm running on a Laptop with 8× AMD Ryzen 7 4800h with radeon graphics + NVidia RTX 3050 in an on-demand profile.

**Comment by itoshkov** [comment]
I also tried the following:

1. I removed switcher from the auto-start
2. Booted with the 5.13.0-28-generic kernel and logged in
3. Started switcher - so far so good
4. Went to System Settings -> Desktop -> Appearance and switched between default and dark a few times.

The system did not change its wallpaper, and after a couple of switches it froze.

**Comment by lukors** [comment]
@itoshkov why do you have that kernel that causes issues? Is that the one the operating system came with? I'm having a really hard time understanding how I can know which is the "default" kernel in elementary.

If this is a problem that comes from using a "non default" kernel it's likely a problem unrelated to the code in Switcher since all it does is "change the wallpaper", so shouldn't lock up the system. Any program that "changes the wallpaper" would likely show the same problem.

In that case it would be a problem for upstream to fix.

Hope we can figure this out, these freezes are scary! :fearful:

**Comment by itoshkov** [comment]
I agree that the freezes are quite weird. 

I am not 100% sure if this is the default kernel now. When I installed elementary OS, the default was 5.11, but it didn't support my WiFi card. 5.13 was available as part of the Ubuntu's [Hardware Enablement (HWE)](https://ubuntu.com/kernel/lifecycle) stack, so it is an official kernel.

**Comment by itoshkov** [comment]
I think it might be caused by the nvidia drivers. It would be nice if somebody with Intel or AMD video card try to reproduce the problem.

**Comment by lukors** [comment]
I have an Intel integrated GPU with kernel `5.13.0-7620-generic` and am not experiencing this issue.

**Comment by diogopessoa** [comment]
Hello everyone!

I installed Switcher again in elementary 6.1 Jólnir and everything is working fine. 

So since we didn't identify what was really causing the system to crash, and now I don't face these problems anymore, what do you think about closing this bug report? 😉

**Comment by JeysonFlores** [comment]
@diogopessoa Seems OK to me. Any new report of this happening again will be delegated to this issue.
