### ISSUE TITLE
Does not change background

### ISSUE THREAD

**Issue by lukors** [JeysonFlores/switcher#2]
It doesn't change the background for me.

https://user-images.githubusercontent.com/1719884/145965986-2ec2ae55-91df-4c12-b017-754eca0ed582.mp4

**Comment by JeysonFlores** [comment]
Try to run the app from the console and check if it throws any errors, that would help me figure out the problem. However it looks like the app doesn't find the image.... which of course it shouldn't happen.

If it doesn't throw anything I'll make a new commit that will add more debugging alerts and stuff that will help us figure out what's the problem.

**Comment by lukors** [comment]
Here's a video of what happens, so you can see what message comes when: 

https://user-images.githubusercontent.com/1719884/146050018-62914868-5d58-43d4-b88b-735c7d95075e.mp4

Here's the log:
```text
Gtk-Message: 18:31:02.220: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:31:02.221: Failed to load module "canberra-gtk-module"

(com.github.jeysonflores.switcher:2): GLib-CRITICAL **: 18:31:09.846: g_variant_new_string: assertion 'string != NULL' failed
error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(com.github.jeysonflores.switcher:2): GLib-CRITICAL **: 18:31:42.845: g_variant_new_string: assertion 'string != NULL' failed
```

**Comment by JeysonFlores** [comment]
Ok, It was because the flatpak container didn't have permissions to access elementary's contractor (the thing the app uses to change the wallpaper). For some reason I didn't realize of this last night (it seems I was quite tired). However with the last commit it should work. Can you try it to see if it works?

**Comment by lukors** [comment]
Looks like it's working now! :)
