### ISSUE TITLE
Switcher doesn't always pick the correct wallpaper on startup

### ISSUE THREAD

**Issue by itoshkov** [JeysonFlores/switcher#20]
##### Way to reproduce:
1. Set the _System Settings_ -> _Desktop_ -> _Appearance_ -> _Style_ to "Sunset to Sunrise".
2. Shutdown the computer while it's in dark mode (Note, it doesn't work with "suspend").
3. Power it up when it's day time.
4. Log in.

##### Expected behavior:
- To see light mode and light wallpaper.

##### Actual behavior:
- The desktop is in light mode but with the dark wallpaper.

##### Workaround:
- Cycling the styles fixes it.

**Comment by itoshkov** [comment]
I just saw that the "Run at startup" switch was off. I'll try it again and report back whether it's a real issue or not.

Of course, I had to see this _after_ I submitted the issue :)

**Comment by itoshkov** [comment]
The issue is present even when "Run at startup" is set.

**Comment by JeysonFlores** [comment]
Hey! Thanks for reporting this issue. Since I haven't work on this for a while (since I'm waiting for eOS 7 to be able to port it to Gtk4) I stopped looking out for bugs. I'm glad that you found this and that you made a PR to fix it. I'll review it gladly!
